services:
  redis:
    image: redis:7-alpine
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 5s
      timeout: 3s
      retries: 10

  app:
    build:
      context: ./json_kv_service
      dockerfile: Dockerfile
    environment:
      KV_API_KEY: ${KV_API_KEY:-change_me}
      REDIS_HOST: redis
      REDIS_PORT: "6379"
      PORT: "8001"
      BIND_HOST: 0.0.0.0
    depends_on:
      redis:
        condition: service_healthy
    ports:
      - "8001:8001"


